# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'socketBasic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for socket_demo
  pod 'Socket.IO-Client-Swift'
  pod 'IQKeyboardManagerSwift'
  pod 'RealmSwift', '~>10'
  
 
end
